---
spring:
   application:
     name: eureka-client-1
server:
  port: 8001

eureka:
  client:
    service-url:
#      For single instance of eureka
#      defaultZone: http://localhost:8010

#      For multiple instance of eureka
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
